apiVersion: v1
kind: Pod
metadata:
  name: curltool
spec:
  containers:
  - name: curltool
    image: curlimages/curl:latest
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
