apiVersion: v1
kind: Pod
metadata:
  name: dnstools
spec:
  containers:
  - name: dnstools
    image: ehazlett/dns-tools:latest #infoblox/dnstools:latest
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

# apk add curl
# apk add openssl