apiVersion: v1
kind: Pod
metadata:
  name: openssltool
spec:
  containers:
  - name: openssltool
    image: ianayoung/openssl:latest
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

# apk add curl